const MENU_PERMISSIONS = {
  OVERVIEW: "overview",
  USER_MANAGEMENT: "user_management",
  ASSETS: "assets",
  ASSET: "asset",
  ASSETS_STOCK: "assets_stock",
  REQUISITION: "requisition",
  PURCHASE: "purchase",
  SALE: "sale",
  DAMAGE: "damage",
  MARKETING: "marketing",
  DM_EXPENSE: "dm_expense",
  ADS_CAMPAIGN_KPI: "ads_campaign_kpi",
  PROFIT_LOSS: "profit_loss",
  AUTO_PROFIT_LOSS: "auto_profit_loss",
  PROFIT_LOSS_USER: "profit_loss_user",
  MANUFACTURE: "manufacture",
  ITEM: "item",
  MANUFACTURE_STOCK: "manufacture_stock",
  MANUFACTURE_MENU: "manufacture_menu",
  STOCK_ADJUSTMENT: "stock_adjustment",
  MIXER: "mixer",
  INVENTORY: "inventory",
  INVENTORY_OVERVIEW: "inventory_overview",
  STOCK_PRODUCT: "stock_product",
  STOCK_ALERT: "stock_alert",
  WAREHOUSE: "warehouse",
  SUPPLIER: "supplier",
  PRODUCT: "product",
  PURCHASE_REQUISITION: "purchase_requisition",
  RECEIVED_PRODUCT: "received_product",
  RECEIVED_RETURN: "received_return",
  INTRANSIT_PRODUCT: "intransit_product",
  SALES_RETURN: "sales_return",
  DAMAGE_MANAGEMENT: "damage_management",
  DAMAGE_STOCK: "damage_stock",
  DAMAGE_PRODUCT: "damage_product",
  DAMAGE_REPAIRING_STOCK: "damage_repairing_stock",
  DAMAGE_REPAIRING: "damage_repairing",
  DAMAGE_REPAIRED: "damage_repaired",
  POS_PANEL: "pos_panel",
  SELL: "sell",
  POS_REPORT: "pos_report",
  ACCOUNTING: "accounting",
  ACCOUNTING_SUPPLIER: "accounting_supplier",
  BOOK: "book",
  PETTY_CASH_REQUISITION: "petty_cash_requisition",
  PETTY_CASH: "petty_cash",
  LOAN: "loan",
  CREDIT_LEDGER: "credit_ledger",
  NOTIFICATIONS: "notifications",
  NOTICE: "notice",
  TASKS: "tasks",
  CHAT: "chat",
  SETTINGS: "settings",
  LOGO: "logo",
  COD_CHANGE: "cod_change",
  COD_CHARGE: "cod_charge",
  DELIVERY_ADVANCE: "delivery_advance",
  DELIVERY_CHARGE: "delivery_charge",
  ROLE_PERMISSIONS: "role_permissions",
  LOG_HISTORY: "log_history",
  HRM: "hrm",
  EMPLOYEE_MANAGEMENT: "employee_management",
  DEPARTMENT_DESIGNATION: "department_designation",
  TEAM_MANAGEMENT: "team_management",
  // Legacy / alias keys used by some frontends during migration:
  DEPARTMENT_MANAGEMENT: "department_management",
  DESIGNATION_MANAGEMENT: "designation_management",
  SHIFT_MANAGEMENT: "shift_management",
  HOLIDAY_MANAGEMENT: "holiday_management",
  ATTENDANCE: "attendance",
  ATTENDANCE_DEVICE: "attendance_device",
  LEAVE_MANAGEMENT: "leave_management",
  DAILY_WORK_REPORTS: "daily_work_reports",
  CS_WORK_REPORTS: "cs_work_reports",
  LOGISTIC_WORK_REPORTS: "logistic_work_reports",
  PAYROLL_MANAGEMENT: "payroll_management",
  PAYSLIP: "payslip",
  EMPLOYEE_PROFILE: "employee_profile",
  HR_PAYROLL: "hr_payroll",
  EMPLOYEE_LIST: "employee_list",
  EMPLOYEE_KPI: "employee_kpi",
  PAYROLL: "payroll",
  PAYROLL_FINE: "payroll_fine",
  EXPIRED_PRODUCT: "expired_product",
  PROFILE: "profile",
};

const ALL_MENU_PERMISSIONS = Object.values(MENU_PERMISSIONS);

const WAZIH_DASHBOARD_MENU_PERMISSIONS = [
  "dashboard",
  "orders",
  "products",
  "supplier",
  "purchase",
  "landing_page",
  "admin_user",
  "admin_roles",
  "admin_permissions",
  "customers",
  "ip_block",
  "website_setting",
  "api_integration",
  "marketing_tools",
  "blogs",
  "banner_ads",
  "expense",
  "reports",
  "cache_clear",
];

const ALL_VALID_MENU_PERMISSIONS = [
  ...new Set([...ALL_MENU_PERMISSIONS, ...WAZIH_DASHBOARD_MENU_PERMISSIONS]),
];

module.exports = {
  MENU_PERMISSIONS,
  ALL_MENU_PERMISSIONS,
  WAZIH_DASHBOARD_MENU_PERMISSIONS,
  ALL_VALID_MENU_PERMISSIONS,
};
